# Generated by Django 5.2.1 on 2025-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_blogpost_created_at_blogpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
