# Generated by Django 5.2.1 on 2025-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cart_user_alter_cartitem_cart'),
        ('products', '0004_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(related_name='saved_by_users', to='products.product'),
        ),
    ]
