# Generated by Django 5.2.1 on 2025-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')]),
        ),
    ]
