# Generated by Django 5.2.1 on 2025-06-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
